#!/bin/sh /etc/rc.common

START=99

start() {
	export HOME=/root USER=root
	local script_path=$HOME/scripts/cron_runner.sh

	[ -f "$script_path" ] || return 0
	[ -x "$script_path" ] || chmod +x "$script_path"

	cd "$HOME" || return 1
	"$script_path" reboot >>"$HOME/logs/reboot.log" 2>&1 &
}
