#!/bin/sh /etc/rc.common

START=99

start() {
	export HOME=/root
	export USER=root

	[ -f /root/scripts/cron_runner.sh ] || return 0
	[ -x /root/scripts/cron_runner.sh ] || chmod +x /root/scripts/cron_runner.sh

	cd /root || return 1
	/root/scripts/cron_runner.sh reboot &
}
