#!/bin/sh /etc/rc.common

START=99
start() {
    local TARGET="/root/scripts/cron_runner.sh"
    if [ -f "$TARGET" ]; then
        if [ ! -x "$TARGET" ]; then
            chmod u+x "$TARGET"
        fi
        "$TARGET" reboot &
    fi
}
