#!/bin/sh

IPV6_ACCEPT_RA_PATH='/proc/sys/net/ipv6/conf/br-lan/accept_ra'

if [ "${ACTION:-}" = 'ifup' ] && [ "${DEVICE:-}" = 'br-lan' ]; then
  if [ -f "${IPV6_ACCEPT_RA_PATH}" ]; then
    CURRENT_RA_VAL=$(cat "${IPV6_ACCEPT_RA_PATH}")

    if [ "${CURRENT_RA_VAL}" -ne 2 ]; then
      printf '2' >"${IPV6_ACCEPT_RA_PATH}"
    fi
  fi
fi

unset IPV6_ACCEPT_RA_PATH CURRENT_RA_VAL
