#!/bin/sh

INIT_SERVICE_PATH='/etc/init.d/cron_reboot'

if [ -f "${INIT_SERVICE_PATH}" ]; then
  if [ ! -x "${INIT_SERVICE_PATH}" ]; then
    chmod +x "${INIT_SERVICE_PATH}"
  fi

  "${INIT_SERVICE_PATH}" enable
fi

unset INIT_SERVICE_PATH
