name: Check

on:
  schedule:
    - cron: 0 16 * * 0
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euxo pipefail {0}
    steps:
      - name: 检出代码
        uses: actions/checkout@v6.0.2

      - name: 获取信息
        id: get
        env:
          IMW_REPO: immortalwrt/immortalwrt
          IMW_BR: openwrt-24.10
        run: |
          imw_sha=$(gh api "/repos/$IMW_REPO/commits/$IMW_BR" -q '.sha')
          echo "cache=$imw_sha" >>"$GITHUB_OUTPUT"

      - name: 缓存校验
        id: cache
        uses: actions/cache@v5.0.5
        with:
          path: .cache
          key: ${{ steps.get.outputs.cache }}

      - name: 触发工作流
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          >.cache
          gh workflow run Build
