name: Delete

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2

      # - name: ghcr.io cleanup action
      #   uses: dataaxiom/ghcr-cleanup-action@v1
      #   with:
      #     keep-n-untagged: 0
      #     keep-n-tagged: 10

      - name: Delete old releases
        uses: sgpublic/delete-release-action@v1.2
        with:
          release-drop: true
          release-keep-count: 10
          draft-drop: false
